<a href="https://colab.research.google.com/github/jaiharish07/JAI-HARISH/blob/main/ML_in_house_prices_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [2]:
data=pd.read_csv("/content/drive/MyDrive/ML PROJECT datasets/boston_house_prices.csv",header=1)

In [3]:
data

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [4]:
x=data.drop(columns='RAD',axis=1)
y=data['RAD']

In [31]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [32]:
model=RandomForestRegressor()

In [33]:
model.fit(x,y)

RandomForestRegressor()

In [34]:
train_prediction=model.predict(x_train)
test_prediction = model.predict(x_test)

In [35]:
train_prediction

array([24.  ,  4.  ,  2.41, 24.  ,  4.  ,  4.98,  4.98,  2.13, 24.  ,
       24.  ,  4.96,  2.93,  8.  , 24.  ,  2.98,  4.  ,  5.94,  5.87,
        6.87,  6.97, 24.  ,  6.  ,  3.  ,  5.02,  3.72,  3.05,  6.91,
        4.79,  2.  ,  4.11,  4.  ,  5.97,  5.  , 24.  ,  5.  ,  4.41,
        1.48,  4.  ,  4.  ,  4.82,  3.73,  4.  , 24.  ,  3.83,  5.  ,
       24.  ,  4.  ,  8.  , 24.  , 24.  ,  3.2 ,  5.99,  3.  ,  4.  ,
       24.  , 24.  ,  3.15, 24.  ,  3.07,  7.74,  5.02,  4.99,  4.99,
        4.01,  5.  , 24.  ,  4.  ,  5.04,  4.26,  5.  ,  4.94,  5.  ,
       23.8 ,  5.98,  5.99,  4.9 ,  4.97,  3.04,  5.2 , 24.  , 24.  ,
       24.  ,  3.91,  8.  , 24.  ,  4.02, 24.  ,  4.02, 24.  ,  5.  ,
        5.86, 24.  , 24.  ,  1.47,  7.  ,  5.02, 24.  ,  5.76,  3.96,
        4.99,  8.  ,  6.23,  4.02,  6.96,  5.76,  5.  ,  3.09,  8.  ,
        5.11,  4.03, 24.  ,  7.  ,  6.  ,  1.66,  6.82, 20.53, 24.  ,
       24.  ,  7.97,  5.  ,  8.  , 24.  , 24.  ,  5.12,  2.26,  4.  ,
       24.  ,  6.91,

In [36]:
test_prediction

array([ 5.  ,  3.92,  4.  ,  4.06, 24.  ,  4.97,  4.  ,  4.  , 24.  ,
        5.89,  4.76,  5.01, 24.  ,  4.59,  4.99, 24.  ,  1.99, 24.  ,
        3.75, 24.  ,  3.  ,  4.06,  4.  ,  1.24, 24.  , 24.  ,  5.18,
       24.  ,  4.  ,  5.95,  5.14,  5.  , 24.  , 24.  , 24.  ,  5.  ,
        2.25,  4.97,  4.01,  4.01,  5.98,  6.28,  3.89,  4.22,  2.14,
       24.  ,  4.  ,  4.1 , 24.  ,  1.76,  5.1 ,  4.86,  4.  ,  5.09,
        4.94, 24.  , 24.  ,  3.96,  3.  ,  6.92,  7.77,  3.9 ,  7.94,
        4.  ,  4.1 ,  4.  , 24.  ,  4.06,  3.2 , 24.  ,  3.  , 24.  ,
       24.  ,  4.57,  4.99, 24.  ,  5.  ,  4.07, 24.  ,  4.  ,  4.36,
       24.  ,  1.68, 24.  ,  4.  ,  8.  , 24.  ,  5.02,  3.79,  4.01,
        4.95, 24.  ,  4.  ,  3.05, 24.  ,  4.  , 24.  , 24.  , 24.  ,
       24.  ,  3.05,  4.99])

In [37]:
train_accuracy = metrics.r2_score(y_train,train_prediction)
test_accuracy = metrics.r2_score(y_test,test_prediction)
print("train_accuracy :",train_accuracy)
print("test_Accuracy :",test_accuracy)

train_accuracy : 0.9970895896779504
test_Accuracy : 0.9995257350084186


In [38]:
input_data=[0.02731,	0.0	,7.07,	0,	0.469	,6.421,	78.9	,4.9671,	242,	17.8,	396.90,	9.14,	21.6]
reshape_data=np.asarray(input_data)
new_input=reshape_data.reshape(1,-1)

In [39]:
new_prediction=model.predict(new_input)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


In [40]:
new_prediction

array([2.25])